// otel-config.js — Araz ERP müşteriye özel kurulum sabitleri.
// Yeni bir müşteri kurulumunda SADECE bu dosya düzenlenir, başka hiçbir
// dosyaya dokunulmaz. auth-guard.js -> supabase-config.js -> otel-config.js
// -> ortak.js sırasında, senkron olarak yüklenir.

const OTEL_ISIMLERI = {'810':'Ali Bey Club Manavgat','811':'Ali Bey Resort Sorgun'};
const OTEL_KISA = {'810':'Club','811':'Resort'};
const OTEL_TICARI_UNVAN = {'810':'GUROK TUR MAD.A.S. (CLUB MANAVGAT)','811':'GUROK TUR MAD.A.S. (RESORT SORGUN)'};
const GRUP_ADI = 'Gürok Turizm Grubu';
const DAHILI_EMAIL_DOMAIN = 'gurok.internal';
const MERKEZI_DEPO = {'810':'100','811':'300'};

function merkeziDepoKodu(otelId){ return MERKEZI_DEPO[otelId] || '100'; }
function otelFromDepoId(depoId){ const i=(depoId||'').indexOf('_'); return i>=0 ? depoId.slice(0,i) : '810'; }

// Bar/Restoran depoları — kod → ad + tip + otel. Bar modülünde masa/garson bu isimleri gösterir.
// otel: hangi otele ait (810 Club Manavgat / 811 Resort Sorgun) — masa eklemede depo listesi otele göre filtrelenir.
const BAR_DEPOLARI = {
  // 810 — Ali Bey Club Manavgat
  'CSM201':{ad:'ALIBEY RESTAURANT',tip:'Restoran',otel:'810'}, 'CSM202':{ad:'PARK RESTAURANT',tip:'Restoran',otel:'810'},
  'CSM204':{ad:'SAHIL RESTAURANT',tip:'Restoran',otel:'810'}, 'CSM205':{ad:'AQUA RESTAURANT',tip:'Restoran',otel:'810'},
  'CSM206':{ad:'KIYI RESTAURANT',tip:'Restoran',otel:'810'},
  'CSM301':{ad:'TURK KAHVESI',tip:'Bar',otel:'810'}, 'CSM302':{ad:'CARDAK',tip:'Bar',otel:'810'}, 'CSM303':{ad:'TALVAR',tip:'Bar',otel:'810'},
  'CSM304':{ad:'POOL',tip:'Bar',otel:'810'}, 'CSM305':{ad:"ALI'S PUB",tip:'Bar',otel:'810'}, 'CSM306':{ad:'TENIS BAR',tip:'Bar',otel:'810'},
  'CSM307':{ad:'KONAK',tip:'Bar',otel:'810'}, 'CSM308':{ad:'KARAGOZ',tip:'Bar',otel:'810'}, 'CSM310':{ad:'ILICA BAR',tip:'Bar',otel:'810'},
  'CSM311':{ad:'HARLEK',tip:'Bar',otel:'810'}, 'CSM312':{ad:'HISAR',tip:'Bar',otel:'810'}, 'CSM313':{ad:'YONCALI',tip:'Bar',otel:'810'},
  'CSM314':{ad:'FRIG BEACH BAR',tip:'Bar',otel:'810'}, 'CSM315':{ad:'PAVILLION BAR',tip:'Bar',otel:'810'}, 'CSM316':{ad:'LOBBY BAR',tip:'Bar',otel:'810'},
  'CSM317':{ad:'PARK TURK KAHVESI',tip:'Bar',otel:'810'}, 'CSM318':{ad:'SARAP VE BIRA EVI',tip:'Bar',otel:'810'},
  // 811 — Ali Bey Resort Sorgun
  'RSM201':{ad:'ALA RESTAURANT',tip:'Restoran',otel:'811'}, 'RSM202':{ad:'RANA RESTAURANT',tip:'Restoran',otel:'811'},
  'RSM203':{ad:'MEHTABE RESTAURANT',tip:'Restoran',otel:'811'}, 'RSM204':{ad:'KEYFI SEFA RESTAURANT',tip:'Restoran',otel:'811'},
  'RSM205':{ad:'KAIGAN SUSHI CORNER',tip:'Restoran',otel:'811'}, 'RSM206':{ad:'KAIGAN TEPPANYAKI A LA CARTE',tip:'Restoran',otel:'811'},
  'RSM207':{ad:'MEHTABE GRILL',tip:'Restoran',otel:'811'}, 'RSM208':{ad:'MEHTABE FISH',tip:'Restoran',otel:'811'},
  'RSM301':{ad:'PEYMANE BAR',tip:'Bar',otel:'811'}, 'RSM302':{ad:'NAZENDE CAFE',tip:'Bar',otel:'811'},
  'RSM303':{ad:'RUMI BAR',tip:'Bar',otel:'811'}, 'RSM304':{ad:'FERASE ALIS PUB',tip:'Bar',otel:'811'},
  'RSM305':{ad:'ENDAME BAR',tip:'Bar',otel:'811'}, 'RSM306':{ad:'LOBBY BAR',tip:'Bar',otel:'811'},
  'RSM307':{ad:'TENIS BAR',tip:'Bar',otel:'811'}, 'RSM308':{ad:'ODA SERVISI',tip:'Bar',otel:'811'},
  'RSM309':{ad:'BEACH BAR',tip:'Bar',otel:'811'}
};
// Depo kodu ERP genelinde otel-önekli tutulur (ör. '810_CSM302'). depoAdi hem önekli
// hem ham ('CSM302') formu çözer: ilk '_' sonrasını bar kodu kabul edip BAR_DEPOLARI'ye bakar.
function depoAdi(kod){
  if(!kod) return '—';
  const i=String(kod).indexOf('_');
  const bar=i>=0 ? String(kod).slice(i+1) : kod;
  return (BAR_DEPOLARI[bar] && BAR_DEPOLARI[bar].ad) ? BAR_DEPOLARI[bar].ad : kod;
}

// Tam depo/departman dizini — ana depo (100/300), teknik depo, mutfak müdürlükleri,
// idari birimler, F&B outlet'leri dahil OTELİN TÜM birimleri. Stok Takip'in depo
// seçicisi ve İç Talepler'in "Departman" listesi bu tek kaynağı kullanır (ikisi de
// aynı gerçek birim/depo evrenine bakmalı — BAR_DEPOLARI sadece F&B alt kümesi).
// Kaynak: LN Infor "Depolar" raporu (08.07.2026 tarihli, Ali Bey Lojistik / Şirket 809).
// Club (810) için gerçek LN Infor kodları (CSM=Servis Müdürlüğü, CMM=Mutfak Müdürlüğü);
// Resort (811) için RB (Bijal alt-bölgesi dahil) ve RSM/RMM kodları kullanılıyor.
const DEPOLAR_810 = [
  { id:'100', ad:'Club Isletme Depo', ikon:'🏭' },
  { id:'200', ad:'Club Teknik Depo', ikon:'🏭' },
  { id:'CEA101', ad:'Eglence Aktivite Idari', ikon:'🎉' },
  { id:'CEA201', ad:'Animasyon', ikon:'🎉' },
  { id:'CEA202', ad:'Teenager Club', ikon:'🎉' },
  { id:'CEA301', ad:'Aquapark', ikon:'🎉' },
  { id:'CEA401', ad:'Fitnes First', ikon:'🎉' },
  { id:'CEA501', ad:'Adventure Park', ikon:'🎉' },
  { id:'CGM101', ad:'Genel Mudurluk Idari', ikon:'🏢' },
  { id:'CIK101', ad:'Insan Kaynaklari Idari', ikon:'👥' },
  { id:'CIK201', ad:'Personel Lojmanlari', ikon:'👥' },
  { id:'CMH101', ad:'Muhasebe Mudurlugu Idari', ikon:'💰' },
  { id:'CMH201', ad:'Muhasebe Yoneticiligi', ikon:'💰' },
  { id:'CMH301', ad:'Maliyet Kontrol Yoneticiligi', ikon:'💰' },
  { id:'CMH401', ad:'Isletme Depo', ikon:'🏭' },
  { id:'CMH501', ad:'Bilgi Islem', ikon:'🏢' },
  { id:'CMK101', ad:'Genel Koordinator', ikon:'🏢' },
  { id:'CMK201', ad:'Mali Isler', ikon:'💰' },
  { id:'CMK301', ad:'Satinalma Mudurlugu', ikon:'🏢' },
  { id:'CMK401', ad:'Standartlar Mudurlugu', ikon:'🏢' },
  { id:'CMK402', ad:'Alibey H&r Kalite VE Guvence M', ikon:'🏢' },
  { id:'CMK501', ad:'Satis Pazarlama Mudurlugu', ikon:'🏢' },
  { id:'CMK602', ad:'Merkez Egitim Gelisim Muduru', ikon:'🏢' },
  { id:'CMK701', ad:'Wellness Yoneticiligi', ikon:'💆' },
  { id:'CMM101', ad:'Mutfak M Idari Ofis', ikon:'🍳' },
  { id:'CMM201', ad:'Anamutfak', ikon:'🍳' },
  { id:'CMM202', ad:'Aqua Mutfak', ikon:'🍳' },
  { id:'CMM203', ad:'Personel Mutfagi', ikon:'📦' },
  { id:'CMM204', ad:'Park Mutfak', ikon:'🍳' },
  { id:'CMM205', ad:'Club Lojm Pers Yemekhanesi', ikon:'📦' },
  { id:'CMM301', ad:'Bulasikhane', ikon:'🍽️' },
  { id:'CMY101', ad:'Mobilyahane', ikon:'📦' },
  { id:'COB101', ad:'Onburo Idari', ikon:'🛎️' },
  { id:'COB201', ad:'Resepsiyon', ikon:'🛎️' },
  { id:'COB301', ad:'Rezervasyon', ikon:'🛎️' },
  { id:'COB401', ad:'Misafir Iliskileri', ikon:'🛎️' },
  { id:'COB501', ad:'Tenis Kortlari', ikon:'🎉' },
  { id:'CSM100', ad:'F&b Mudurlugu Ofis', ikon:'📦' },
  { id:'CSM101', ad:'Club F&b Mudurlugu', ikon:'📦' },
  { id:'CSM201', ad:'Alibey Restaurant', ikon:'🍽️' },
  { id:'CSM202', ad:'Park Restaurant', ikon:'🍽️' },
  { id:'CSM203', ad:'Doner Restaurant', ikon:'🍽️' },
  { id:'CSM204', ad:'Sahil Restaurant', ikon:'🍽️' },
  { id:'CSM205', ad:'Aqua Restaurant', ikon:'🍽️' },
  { id:'CSM206', ad:'Kiyi Restaurant', ikon:'🍽️' },
  { id:'CSM207', ad:'Kaigan Teppanyaki A LA Carte', ikon:'🍽️' },
  { id:'CSM301', ad:'Turk Kahvesi', ikon:'🍹' },
  { id:'CSM302', ad:'Cardak', ikon:'🍹' },
  { id:'CSM303', ad:'Talvar', ikon:'🍹' },
  { id:'CSM304', ad:'Pool', ikon:'📦' },
  { id:'CSM305', ad:'Ali\'s Pub', ikon:'🍹' },
  { id:'CSM306', ad:'Tenis Bar', ikon:'🍹' },
  { id:'CSM307', ad:'Konak', ikon:'🍹' },
  { id:'CSM308', ad:'Karagoz', ikon:'🍹' },
  { id:'CSM309', ad:'Aqua Bar', ikon:'🍹' },
  { id:'CSM310', ad:'Ilica Bar', ikon:'🍹' },
  { id:'CSM311', ad:'Harlek', ikon:'🍹' },
  { id:'CSM312', ad:'Hisar', ikon:'🍹' },
  { id:'CSM313', ad:'Yoncali', ikon:'🍹' },
  { id:'CSM314', ad:'Frig Beach Bar', ikon:'🍹' },
  { id:'CSM315', ad:'Pavillion Bar', ikon:'🍹' },
  { id:'CSM316', ad:'Lobby Bar', ikon:'🍹' },
  { id:'CSM317', ad:'Park Turk Kahvesi', ikon:'🍹' },
  { id:'CSM318', ad:'Sarap VE Bira Evi', ikon:'📦' },
  { id:'CSM401', ad:'Resepsiyon Cay Ocagi', ikon:'☕' },
  { id:'CSM402', ad:'Park Resepsiyon Cay Ocagi', ikon:'☕' },
  { id:'CSM403', ad:'Idari Bina Cay Ocagi', ikon:'☕' },
  { id:'CTG101', ad:'Tur.grp.direktorlugu', ikon:'🏢' },
  { id:'CTG301', ad:'Tur.grp.kalite VE Guvence Dire', ikon:'🏢' },
  { id:'CTG401', ad:'Tur.grp.satis VE Pazarlama Dir', ikon:'🏢' },
  { id:'CTG501', ad:'Tur.grp.insan Kaynaklari Direk', ikon:'👥' },
  { id:'CTG502', ad:'Tur.grp.egitim Gelisim Muduru', ikon:'🏢' },
  { id:'CTG601', ad:'Tur.grp.satinalma Direktorlugu', ikon:'🏢' },
  { id:'CTG701', ad:'Tur.grp.mali Isler Direktorlug', ikon:'💰' },
  { id:'CTG801', ad:'Turkiye Kurumsal Iliskiler Mud', ikon:'🏢' },
  { id:'CTM101', ad:'Teknik Servis Mud Idari', ikon:'🔧' },
  { id:'CTM201', ad:'Mekanik', ikon:'🔧' },
  { id:'CTM301', ad:'Elektrik', ikon:'🔧' },
  { id:'CTM401', ad:'Insaat', ikon:'🔧' },
  { id:'CYA101', ad:'Yasam Alanlari Idari', ikon:'📦' },
  { id:'CYA201', ad:'Kat Hizmetleri', ikon:'🛏️' },
  { id:'CYA202', ad:'Odalar', ikon:'🛏️' },
  { id:'CYA301', ad:'Camasirhane', ikon:'👔' },
  { id:'CYA302', ad:'Terzi', ikon:'👔' },
  { id:'CYA401', ad:'Guvenlik', ikon:'🛡️' },
  { id:'CYA501', ad:'Bahce', ikon:'🌳' },
  { id:'CYA601', ad:'Magazalar Butik', ikon:'🛍️' },
  { id:'CYA602', ad:'Hamam Sauna - Spa', ikon:'💆' },
  { id:'CZC101', ad:'Yat-katamaran', ikon:'⛵' },
];

const DEPOLAR_811 = [
  { id:'300', ad:'Resort Isletme Depo', ikon:'🏭' },
  { id:'400', ad:'Resort Teknik Depo', ikon:'🏭' },
  { id:'RBEA21', ad:'Bijal Animasyon', ikon:'🎉' },
  { id:'RBEA41', ad:'Bijal Fitness', ikon:'🎉' },
  { id:'RBEA61', ad:'Bijal Spa', ikon:'💆' },
  { id:'RBGM11', ad:'Bijal Genel Mudurluk', ikon:'🏢' },
  { id:'RBKG11', ad:'Kalite Guvence Yoneticiligi', ikon:'🏢' },
  { id:'RBMK51', ad:'Bijal Satis Pazarlama', ikon:'🏢' },
  { id:'RBMM11', ad:'Bijal Mutfak Mudurlugu', ikon:'🍳' },
  { id:'RBMM21', ad:'Beach House Mutfak', ikon:'🍳' },
  { id:'RBMM22', ad:'Club House Mutfak', ikon:'🍳' },
  { id:'RBMM23', ad:'Bijal Personel Mutfagi', ikon:'📦' },
  { id:'RBMM31', ad:'Bijal Bulasikhane', ikon:'🍽️' },
  { id:'RBOB11', ad:'Bijal Onburo', ikon:'🛎️' },
  { id:'RBSM11', ad:'Bijal Servis Mudurlugu Idari', ikon:'📦' },
  { id:'RBSM21', ad:'Beach House Servis', ikon:'📦' },
  { id:'RBSM22', ad:'Club House Servis', ikon:'📦' },
  { id:'RBSM26', ad:'Bijal Teppanyaki A LA Carte', ikon:'🍽️' },
  { id:'RBSM31', ad:'IN Villa Dinning', ikon:'📦' },
  { id:'RBSM41', ad:'Bijal Cay Ocaklari', ikon:'☕' },
  { id:'RBTM11', ad:'Bijal Teknik Mudurluk Idari', ikon:'🔧' },
  { id:'RBTM21', ad:'Bijal Mekanik', ikon:'🔧' },
  { id:'RBTM31', ad:'Bijal Elektrik', ikon:'🔧' },
  { id:'RBTM41', ad:'Bijal Insaat', ikon:'🔧' },
  { id:'RBYA21', ad:'Bijal Kat Hizmetleri', ikon:'🛏️' },
  { id:'RBYA22', ad:'Bijal Odalar', ikon:'🛏️' },
  { id:'RBYA31', ad:'Bijal Camasirhane', ikon:'👔' },
  { id:'RBYA51', ad:'Bijal Bahce', ikon:'🌳' },
  { id:'RBYA61', ad:'Bijal Butik', ikon:'🛍️' },
  { id:'REA101', ad:'Eglence VE Aktiviteler Idari', ikon:'🎉' },
  { id:'REA201', ad:'Animasyon', ikon:'🎉' },
  { id:'REA301', ad:'Aquapark', ikon:'🎉' },
  { id:'REA401', ad:'Fitness First', ikon:'🎉' },
  { id:'REA501', ad:'Tenis Kortlari', ikon:'🎉' },
  { id:'REA601', ad:'Samara Spa', ikon:'💆' },
  { id:'RGM101', ad:'Genel Mudurluk Idari', ikon:'🏢' },
  { id:'RIK101', ad:'Insan Kaynaklari Idari', ikon:'👥' },
  { id:'RIK201', ad:'Personel Lojmani', ikon:'👥' },
  { id:'RIK202', ad:'Personel Kantini', ikon:'📦' },
  { id:'RMH101', ad:'Muhasebe Mudurlugu Idari', ikon:'💰' },
  { id:'RMH201', ad:'Muhasebe Yoneticiligi', ikon:'💰' },
  { id:'RMH301', ad:'Maliyet Kontrol Yoneticiligi', ikon:'💰' },
  { id:'RMH401', ad:'Isletme Depo', ikon:'🏭' },
  { id:'RMH501', ad:'Bilgi Islem', ikon:'🏢' },
  { id:'RMK101', ad:'Genel Koordinator', ikon:'🏢' },
  { id:'RMK201', ad:'Mali Isler', ikon:'💰' },
  { id:'RMK301', ad:'Satinalma Mudurlugu', ikon:'🏢' },
  { id:'RMK401', ad:'Standartlar Mudurlugu', ikon:'🏢' },
  { id:'RMK402', ad:'Alibey H&r Kalite VE Guvence M', ikon:'🏢' },
  { id:'RMK501', ad:'Satis Pazarlama Mudurlugu', ikon:'🏢' },
  { id:'RMK601', ad:'Insan Kaynaklari Mudurlugu', ikon:'👥' },
  { id:'RMK602', ad:'Merkez Egitim Gelisim Muduru', ikon:'🏢' },
  { id:'RMK701', ad:'Wellness Yoneticiligi', ikon:'💆' },
  { id:'RMM101', ad:'Mutfak Mudurlugu Idari', ikon:'🍳' },
  { id:'RMM201', ad:'Anamutfak', ikon:'🍳' },
  { id:'RMM202', ad:'Aqua Mutfak', ikon:'🍳' },
  { id:'RMM203', ad:'Personel Mutfagi', ikon:'📦' },
  { id:'RMM204', ad:'Lojman Personel Mutfagi', ikon:'👥' },
  { id:'RMM301', ad:'Bulasikhane', ikon:'🍽️' },
  { id:'ROB101', ad:'Onburo Idari', ikon:'🛎️' },
  { id:'ROB201', ad:'Resepsiyon', ikon:'🛎️' },
  { id:'ROB301', ad:'Rezervasyon', ikon:'🛎️' },
  { id:'ROB401', ad:'Misafir Iliskileri', ikon:'🛎️' },
  { id:'RSM101', ad:'Servis Mudurlugu Idari', ikon:'📦' },
  { id:'RSM201', ad:'Ala Restaurant', ikon:'🍽️' },
  { id:'RSM202', ad:'Rana Restaurant', ikon:'🍽️' },
  { id:'RSM203', ad:'Mehtabe Restaurant', ikon:'🍽️' },
  { id:'RSM204', ad:'Keyfi Sefa Restaurant', ikon:'🍽️' },
  { id:'RSM205', ad:'Kaigan Sushi Corner', ikon:'🍽️' },
  { id:'RSM206', ad:'Kaigan Teppanyaki A LA Carte', ikon:'🍽️' },
  { id:'RSM207', ad:'Mehtabe Grill', ikon:'🍽️' },
  { id:'RSM208', ad:'Mehtabe Fish', ikon:'🍽️' },
  { id:'RSM301', ad:'Peymane Bar', ikon:'🍹' },
  { id:'RSM302', ad:'Nazende Cafe', ikon:'🍹' },
  { id:'RSM303', ad:'Rumi Bar', ikon:'🍹' },
  { id:'RSM304', ad:'Ferase Alis Pub', ikon:'🍹' },
  { id:'RSM305', ad:'Endame Bar', ikon:'🍹' },
  { id:'RSM306', ad:'Lobby Bar', ikon:'🍹' },
  { id:'RSM307', ad:'Tenis Bar', ikon:'🍹' },
  { id:'RSM308', ad:'Oda Servisi', ikon:'📦' },
  { id:'RSM309', ad:'Beach Bar', ikon:'🍹' },
  { id:'RSM401', ad:'Cay Ocaklari', ikon:'☕' },
  { id:'RTG101', ad:'Tur.grp.direktorlugu', ikon:'🏢' },
  { id:'RTG301', ad:'Tur.grp.kalite VE Guvence Dire', ikon:'🏢' },
  { id:'RTG401', ad:'Tur.grp.satis VE Pazarlama Dir', ikon:'🏢' },
  { id:'RTG501', ad:'Tur.grp.insan Kaynaklari Direk', ikon:'👥' },
  { id:'RTG502', ad:'Tur.grp.egitim Gelisim Muduru', ikon:'🏢' },
  { id:'RTG601', ad:'Tur.grp.satinalma Direktorlugu', ikon:'🏢' },
  { id:'RTG701', ad:'Tur.grp.mali Isler Direktorlug', ikon:'💰' },
  { id:'RTG801', ad:'Turkiye Kurumsal Iliskiler Mud', ikon:'🏢' },
  { id:'RTM101', ad:'Teknik Mudurluk Idari', ikon:'🔧' },
  { id:'RTM201', ad:'Mekanik', ikon:'🔧' },
  { id:'RTM301', ad:'Elektrik', ikon:'🔧' },
  { id:'RTM401', ad:'Insaat', ikon:'🔧' },
  { id:'RYA101', ad:'Yasam Alanlari Idari', ikon:'📦' },
  { id:'RYA201', ad:'Kat Hizmetleri', ikon:'🛏️' },
  { id:'RYA202', ad:'Odalar', ikon:'🛏️' },
  { id:'RYA301', ad:'Camasirhane', ikon:'👔' },
  { id:'RYA302', ad:'Terzi', ikon:'👔' },
  { id:'RYA401', ad:'Guvenlik', ikon:'🛡️' },
  { id:'RYA501', ad:'Bahce', ikon:'🌳' },
  { id:'RYA601', ad:'Magazalar', ikon:'🛍️' },
];

function depolarForOtel(otelId){ return otelId==='810'?DEPOLAR_810:DEPOLAR_811; }
