-- ============================================================================
-- rls_auto_enable() EVENT TRIGGER'A BAĞLANMASI
-- Tarih: 2026-09-08
--
-- ############################################################################
-- #                                                                          #
-- #   G E R E K S İ Z   —   Ç A L I Ş T I R M A                              #
-- #                                                                          #
-- #   Ag ZATEN BAĞLI. Üretimde `ensure_rls` adlı event trigger mevcut,        #
-- #   açık ve `public.rls_auto_enable()` fonksiyonuna bağlı.                  #
-- #                                                                          #
-- #   Bu dosya çalıştırılırsa İKİNCİ bir event trigger yaratmaya çalışır      #
-- #   (adı farklı olduğu için buradaki varlık kontrolü onu göremez) ve        #
-- #   `postgres` superuser olmadığı için "permission denied" ile patlar.      #
-- #                                                                          #
-- #   Dosya, YANLIŞ TEŞHİSİN kaydı olarak korunuyor. Silinmiyor: neyi        #
-- #   neden yanlış bildiğimiz, doğrusu kadar öğretici.                        #
-- #                                                                          #
-- ############################################################################
--
-- ---------------------------------------------------------------------------
-- YANLIŞ TEŞHİS — 2026-07-22'den 2026-09-08'e
-- ---------------------------------------------------------------------------
-- Altı hafta boyunca "rls_auto_enable yazılmış ama event trigger'a hiç
-- bağlanmamış" diye taşındı. Bu inanç şuralara yazıldı: 2026-07-22 RLS
-- denetimi, `2026-09-01-rls-auto-enable-baglama.sql`, ajan hafızası ve
-- 2026-09-08'de bu dosyanın ilk hâli.
--
-- 2026-09-08'de `2026-09-08-event-trigger-yetki-sondasi.sql` üretimde
-- çalıştırıldı ve gerçek ortaya çıktı:
--
--   | ensure_rls | sahip=postgres | durum=acik | ddl_command_end -> rls_auto_enable() |
--
-- Ağ baştan beri çalışıyormuş. Aynı sondanın 5. bloğu bunu bağımsız olarak
-- doğruluyor: `public` şemasındaki **75 tablonun 75'inde de RLS açık**,
-- kapalı tablo YOK.
--
-- ---------------------------------------------------------------------------
-- KÖK NEDEN — neden göremedik
-- ---------------------------------------------------------------------------
-- Taban şema dökümümüz event trigger'ları İÇERMİYOR:
--
--   pg_dump --schema=public --schema=phase0_private ...
--
-- `--schema` filtresi verildiğinde pg_dump, veritabanı düzeyindeki nesneleri
-- — event trigger'lar dâhil — dökmez. `2026-09-07-post-pms-faz1-sema-dokumu.sql`
-- içinde "event trigger" ifadesi **sıfır kez** geçer; `ensure_rls` repoda
-- HİÇBİR dosyada geçmez.
--
-- Yani taban dosyamız bu nesne sınıfına YAPISAL OLARAK KÖRDÜ. Eşitlik
-- doğrulayıcısı da, üretim parmak izi de event trigger ölçmüyordu. Üretimde
-- var olan bir nesneyi "yok" sanmamızın sebebi bir yanlış okuma değil,
-- ölçüm aracının kapsamıydı.
--
-- Bu, projenin tekrar eden dersinin bir başka biçimi: **ölçülmeyen şey
-- yoktur sanılır.** Phase 0'ın `notice` ile geçen revoke'u da böyleydi.
--
-- ---------------------------------------------------------------------------
-- ALINAN ÖNLEM
-- ---------------------------------------------------------------------------
-- `2026-09-08-event-trigger-tabani.sql` — event trigger'ları kalıcı ölçüm
-- kapsamına alan salt-okuma kontrolü. Yedi tetikleyicinin tabanı sabitlendi;
-- biri eklenir, silinir ya da devre dışı bırakılırsa artık görülür.
--
-- ---------------------------------------------------------------------------
-- YİNE DE NEDEN SİLİNMİYOR
-- ---------------------------------------------------------------------------
-- İçindeki SQL, superuser'ın bulunduğu ortamlarda (self-hosted kurulum,
-- yerel staging) hâlâ geçerlidir: orada `ensure_rls` kendiliğinden gelmez.
-- Aşağıda yorum içinde saklanıyor.
-- ============================================================================


-- ============================================================================
-- ARŞİV — yalnız superuser'ın olduğu ortamlar için (Supabase'de GEREKSİZ)
-- ----------------------------------------------------------------------------
-- do $$
-- begin
--   if exists (select 1 from pg_event_trigger e
--                join pg_proc p on p.oid = e.evtfoid
--                join pg_namespace n on n.oid = p.pronamespace
--               where n.nspname = 'public' and p.proname = 'rls_auto_enable') then
--     raise notice 'rls_auto_enable zaten bir event trigger a bagli; atlandi.';
--     return;
--   end if;
--
--   execute $ddl$
--     create event trigger rls_auto_enable_trg
--       on ddl_command_end
--       when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
--       execute function public.rls_auto_enable()
--   $ddl$;
-- end;
-- $$;
--
-- NOT: Varlık kontrolü ADA göre değil, FONKSİYONA göre yapılır. İlk hâli
-- `evtname = 'rls_auto_enable_trg'` diye bakıyordu ve üretimdeki `ensure_rls`
-- adlı tetikleyiciyi göremezdi — yanlış teşhisi migration'a taşıyacak olan
-- hata tam olarak buydu.
-- ============================================================================


-- ============================================================================
-- AĞIN KAPSAM SINIRI — bağlı olması her şeyi çözmez
-- ----------------------------------------------------------------------------
-- 1. Yalnız RLS'i AÇAR, politika EKLEMEZ. Yeni tablo "RLS açık + 0 politika"
--    = herkese kapalı doğar. Güvenli yön, ama SESSİZ: ekran hata vermez,
--    boş gelir. `urun_birim_donusum` ve `gelen_efaturalar` aylarca böyle
--    ölü kaldı — ve şimdi biliyoruz ki ağ o sırada ÇALIŞIYORDU. Yani o
--    olaylar ağın yokluğundan değil, ağın bu sınırından kaynaklandı.
--
-- 2. Yalnız `public` şeması (fonksiyon gövdesindeki şema listesi).
--
-- 3. Yalnız YENİ `CREATE TABLE` olayları; geçmiş tabloları düzeltmez.
--
-- 4. `supabase_admin`'in yarattığı tablolarda çalışacağı GARANTİ DEĞİL.
--    `rls_auto_enable()` SECURITY DEFINER'dır ve sahibinin yetkisiyle
--    `alter table ... enable row level security` çalıştırır. Tablonun sahibi
--    `supabase_admin` ise fonksiyon sahibi o tabloyu değiştiremeyebilir;
--    gövde `exception when others` ile sarılı olduğu için hata SESSİZCE
--    yutulur ve yalnız `raise log` yazılır.
--
--    Bu yüzden varsayılan ACL P3'ü "çözüldü" saymıyoruz. Ağ riski
--    AZALTIR, sıfırlamaz. Karar kriteri hâlâ ACL uyarı kontrolündeki
--    D1/D2 fiili ölçümüdür.
-- ============================================================================
